### ISSUE TITLE
Errors found in running ./build.sh

### ISSUE THREAD

**Issue by Owen-Liuyuxuan** [TRAILab/CaDDN#18]
Thank you for sharing your code.
During the last step of docker building, I met with the following problem: 

![caddn_build_error](https://user-images.githubusercontent.com/31618608/112259702-b211c900-8ca3-11eb-801e-bab09f8a9af4.png)

My local machine is CUDA 11.2. 
![current_cuda](https://user-images.githubusercontent.com/31618608/112259776-cf469780-8ca3-11eb-928d-b662aceebd08.png)

I am not sure if it is related to my local cuda.

**Comment by codyreading** [comment]
Did you follow all the steps outlined here? https://github.com/TRAILab/CaDDN/blob/master/docker/DOCKER.md. It looks like the docker build isn't able to find your GPU in the Docker Environment, which is solved by the steps outlined here.

Alternatively, you can just do `docker pull codyreading/caddn` rather than building yourself. I recommend this approach.

**Comment by Owen-Liuyuxuan** [comment]
I am not sure. But I have been using docker with Cuda for a while. So I assume I can skip the steps before building.

**Comment by codyreading** [comment]
Nope, there is a step there that allows GPU access in the build phase which is needed for building pcdet.

**Comment by Owen-Liuyuxuan** [comment]
Thank you very much for patiently solving this problem, and it guides me to learn more about docker :pray: . 

For now I may close this issue. :smile:
