### ISSUE TITLE
about dist_test.sh

### ISSUE THREAD

**Issue by rockywind** [TRAILab/CaDDN#31]
Thanks for your contribution!

When I run the script dist_test.sh, what value should be set about PY_ARGS.
![image](https://user-images.githubusercontent.com/14838781/120276724-a5ce6b80-c2e5-11eb-9e15-caf009e88639.png)

**Comment by codyreading** [comment]
Hello!

If you run `python test.py -h`, you can see all of the different command line arguments. These allow you to set the model checkpoint, batch_size, etc. You can fill these arguments here.

**Comment by codyreading** [comment]
Take a look at the instructions here: https://github.com/TRAILab/CaDDN/blob/master/docs/GETTING_STARTED.md#test-and-evaluate-the-pretrained-models

**Comment by rockywind** [comment]
Thank you very much!
I met the  problem, when I run the dist_test.sh.
![image](https://user-images.githubusercontent.com/14838781/120528312-e32e1880-c40d-11eb-9429-9cf5741f4960.png)

**Comment by codyreading** [comment]
Hello,

You didn't enter in any command line arguments as shown [here](https://github.com/TRAILab/CaDDN/blob/master/docs/GETTING_STARTED.md#test-and-evaluate-the-pretrained-models). Addditionally, try using `bash` rather than `sh`:
```
bash scripts/dist_test.sh 4 --cfg_file cfgs/kitti_models/CaDDN.yaml
```

Seems like this error occurs with `sh` and not with `bash`. I'll update this in the docs for the next release.

**Comment by rockywind** [comment]
Thanks for your help! It works.
