### ISSUE TITLE
How to draw the smear effect 

### ISSUE THREAD

**Issue by tonyyang1995** [TRAILab/CaDDN#48]
Thanks for sharing the codes. Just wonder how to draw the smear effect as Figure 1 show in the papers?
![image](https://user-images.githubusercontent.com/44078072/124046843-dbe43580-d9e0-11eb-9c10-fd70945fd5eb.png)

**Comment by codyreading** [comment]
Hello!

Figures (b) and (c) here were generated by plotting the BEV features generated by CaDDN. That would be `batch_dict["spatial_features"]` stored in the batch dict. Figure (c) should be able to be plot easily, but Figure (b) was done manually setting the depth distributions to ones [here](https://github.com/TRAILab/CaDDN/blob/master/pcdet/models/backbones_3d/ffe/depth_ffe.py#L87) rather than using the estimated values.

**Comment by tonyyang1995** [comment]
Thanks, that helps a lot.

**Comment by rockywind** [comment]
Thanks for your help on the previous issue.
I drew the smear effect image. I found that the BEV heatmap's coordination was not in conformity with the raw image. The final result was correct. I found there is exist a horizontal flip in the BEV heatmap.
![image](https://user-images.githubusercontent.com/14838781/124341963-e8d87300-dbf2-11eb-98a1-69b31360a4f1.png)

**Comment by rockywind** [comment]
I rotated the BEV heatmap's angle to consistency with the raw image. There exists a horizontal flip in the BEV heatmap.
![image](https://user-images.githubusercontent.com/14838781/124342046-7e740280-dbf3-11eb-8bef-9ce9f705db9f.png)

**Comment by codyreading** [comment]
Hi @rockywind,

Yes this is expected. This has to do with the difference between the LiDAR and camera reference frame, which are rotated and pointed in a different direction relative to one another. In order to visualize you need to perform this rotations + flip, but the transformation is still correct in the underlying code.

**Comment by rockywind** [comment]
Thanks, that helps a lot. @codyreading
