### ISSUE TITLE
I test the caddn.pth model, the moderate model 3D AP is 15.93, but the site say it's 16.07.

### ISSUE THREAD

**Issue by rockywind** [TRAILab/CaDDN#70]
My Environment is:
ubuntu 16.04
cuda11.1
pytorch1.7.1
Per_GPU_batch_size=4
GPU_num=4

> 2021-09-10 11:25:34,568   INFO  
Car AP@0.70, 0.70, 0.70:
bbox AP:89.9561, 80.0459, 78.7131
bev  AP:34.7719, 25.4463, 24.0320
3d   AP:27.8585, 21.2847, 18.5648
aos  AP:89.11, 78.92, 76.98
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:95.3015, 82.5968, 77.3852
bev  AP:31.3691, 21.3940, 19.2927
3d   AP:23.5936, 15.9324, 13.4591
aos  AP:94.28, 81.29, 75.64
Car AP@0.70, 0.50, 0.50:
bbox AP:89.9561, 80.0459, 78.7131
bev  AP:62.5091, 46.2527, 44.8870
3d   AP:57.8045, 43.3583, 37.7294
aos  AP:89.11, 78.92, 76.98
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:95.3015, 82.5968, 77.3852
bev  AP:62.8995, 46.3063, 42.3390
3d   AP:57.0173, 40.6578, 36.8525
aos  AP:94.28, 81.29, 75.64

**Comment by codyreading** [comment]
It's possible that there are small floating point differences due to different environment versions/hardware. I've experienced different results when running the exact same code with different environments/hardware, and have achieved slightly different results. This difference is quite negligible, I wouldn't worry about it.

**Comment by rockywind** [comment]
The result is that I tested the pre-train model downloaded from GitHub.
The setting is:
per_GPU_size=4
GPU_num=3
![image](https://user-images.githubusercontent.com/14838781/132873629-1524ad8f-6539-4def-984b-e43f1bf80338.png)

**Comment by codyreading** [comment]
Okay that looks good.
