### ISSUE TITLE
Error during testing

### ISSUE THREAD

**Issue by aveen-d** [TRAILab/CaDDN#87]
When I run the test.py file I get the following error. Can you please resolve this?
![3der1](https://user-images.githubusercontent.com/25226325/139681247-2011dfee-ea78-4a49-8284-14f4db88896c.png)

**Comment by codyreading** [comment]
Hello,

I've seen this error previously when compiling [spconv](https://github.com/traveller59/spconv) on one machine and trying to use it on another, where the issue was that the spconv library was compiled for one GPU architecture but then used on another. My recommendation is to investigate what is causing this issue specifically

**Comment by aveen-d** [comment]
Thanks, it worked

**Comment by czy341181** [comment]
Hi, @aveen-d @codyreading  , I also met this problem. I found that it generated an error when calling the nms_gpu function.

https://github.com/TRAILab/CaDDN/blob/5a96b37f16b3c29dd2509507b1cdfdff5d53c558/pcdet/ops/iou3d_nms/src/iou3d_nms.cpp#L133

how you solved it?

**Comment by czy341181** [comment]
I only have one machine, why would I have this problem
